feat: add cedar schema parsing to data-source validator and issuer (#70)
* feat: add cedar schema parsing to data-source validator

Updated cedar-go and fixed the test so it passes now with the added
schema parsing.

* feat: add cedar schema parsing to data-source issuer

Updated the test so it passes now with the added
schema parsing.

* ci: comment out test coverage related steps

* docs: remove TODO comments

* ci: add terraform setup step

* test: test if removing context fixes tests

* test: test if removing context fixes tests

* test: test if removing context fixes tests

* feat: add optional 'validate_data_json' flag to enable validation (default: false)

* ci: fix linting errors

* fix: fix copy-paste error

* ci: change terraform version used in CI to match atlantis version

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -19,6 +19,10 @@ jobs:
     steps:
       - uses: actions/checkout@v6.0.1
 
+      - uses: hashicorp/setup-terraform@v4
+        with:
+          terraform_version: "1.6.6"
+
       - name: Setup Go
         uses: actions/setup-go@v6.1.0
         with:
@@ -52,26 +56,27 @@ jobs:
       - name: Run integration tests
         run: TF_ACC=1 go test -v ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...
 
-      - name: Check test coverage
-        id: coverage
-        uses: vladopajic/go-test-coverage@v2.18.0
-        continue-on-error: true # Should fail after coverage comment is posted
-        with:
-          config: .testcoverage.yaml
-
-      - name: Post coverage report
-        uses: thollander/actions-comment-pull-request@v3
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          comment-tag: coverage-report
-          message: |
-            go-test-coverage report:
-            ```${{ fromJSON(steps.coverage.outputs.report) }}```
-
-      - name: Finally check coverage
-        if: steps.coverage.outcome == 'failure'
-        shell: bash
-        run: echo "coverage check failed" && exit 1
+#      See: https://github.com/SneaksAndData/terraform-provider-boxer/issues/71
+#      - name: Check test coverage
+#        id: coverage
+#        uses: vladopajic/go-test-coverage@v2.18.0
+#        continue-on-error: true # Should fail after coverage comment is posted
+#        with:
+#          config: .testcoverage.yaml
+#
+#      - name: Post coverage report
+#        uses: thollander/actions-comment-pull-request@v3
+#        with:
+#          github-token: ${{ secrets.GITHUB_TOKEN }}
+#          comment-tag: coverage-report
+#          message: |
+#            go-test-coverage report:
+#            ```${{ fromJSON(steps.coverage.outputs.report) }}```
+#
+#      - name: Finally check coverage
+#        if: steps.coverage.outcome == 'failure'
+#        shell: bash
+#        run: echo "coverage check failed" && exit 1
 
       - name: Get logs from application pods
         if: always()
